# Generated by Django 4.2.7 on 2024-03-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studytrackerapp', '0002_remove_assignment_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
