# Generated by Django 4.2.7 on 2024-03-29 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studytrackerapp', '0003_remove_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='due_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title',
        ),
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.CharField(default=datetime.datetime(2024, 3, 29, 22, 58, 15, 495657, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
